#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
UNITY = ROOT / "unity"
VCR = UNITY / "Assets" / "VCR"

parser = argparse.ArgumentParser(
    description="Validate repository structure and Unity project reproducibility evidence."
)
parser.add_argument(
    "--strict-reproducibility",
    action="store_true",
    help=(
        "Treat missing Unity-generated reproducibility files as errors. "
        "Use this for release/promotion gates after opening the project with the pinned editor."
    ),
)
args = parser.parse_args()

errors: list[str] = []
warnings: list[str] = []


def require(path: Path, label: str | None = None) -> None:
    if not path.is_file():
        errors.append(f"missing required file: {label or path.relative_to(ROOT)}")


def load_json(path: Path) -> dict:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception as exc:
        errors.append(f"invalid JSON: {path.relative_to(ROOT)}: {exc}")
        return {}


require(UNITY / "ProjectSettings" / "ProjectVersion.txt")
require(UNITY / "Packages" / "manifest.json")
require(ROOT / "tools" / "bootstrap-mediapipe.sh")
require(ROOT / "tools" / "bootstrap-mediapipe.ps1")

required_latest_chain = [
    VCR / "Editor" / "P11" / "P11BatchValidation.cs",
    VCR / "Editor" / "P11" / "VCR.Editor.P11.asmdef",
    VCR / "Editor" / "P12" / "P12BatchValidation.cs",
    VCR / "Editor" / "P12" / "VCR.Editor.P12.asmdef",
    VCR / "Editor" / "P13" / "P13BatchValidation.cs",
    VCR / "Editor" / "P13" / "VCR.Editor.P13.asmdef",
    ROOT / "tools" / "validate-p12-source-free.sh",
    ROOT / "tools" / "validate-p12-source-free.ps1",
    ROOT / "tools" / "validate-p13-source-free.sh",
    ROOT / "tools" / "validate-p13-source-free.ps1",
]
for path in required_latest_chain:
    require(path)

if VCR.is_dir():
    for path in VCR.rglob("*"):
        if not path.is_file():
            continue

        if path.suffix in {".cs", ".asmdef"}:
            if path.stat().st_size == 0:
                errors.append(f"empty source file: {path.relative_to(ROOT)}")

            meta = Path(str(path) + ".meta")
            if not meta.is_file():
                errors.append(f"missing Unity meta file: {meta.relative_to(ROOT)}")
            elif meta.stat().st_size == 0:
                errors.append(f"empty Unity meta file: {meta.relative_to(ROOT)}")
            else:
                meta_text = meta.read_text(encoding="utf-8", errors="replace")
                if "fileFormatVersion:" not in meta_text or "guid:" not in meta_text:
                    errors.append(
                        f"invalid Unity meta file: {meta.relative_to(ROOT)} "
                        "(missing fileFormatVersion or guid)"
                    )

        if path.suffix == ".asmdef":
            document = load_json(path)
            if document and not document.get("name"):
                errors.append(f"assembly definition has no name: {path.relative_to(ROOT)}")

manifest_path = UNITY / "Packages" / "manifest.json"
if manifest_path.is_file():
    manifest = load_json(manifest_path)
    dependencies = manifest.get("dependencies", {})
    mediapipe = dependencies.get("com.github.homuler.mediapipe")
    expected = "file:LocalPackages/com.github.homuler.mediapipe-0.16.3.tgz"
    if mediapipe != expected:
        errors.append(
            "MediaPipe manifest dependency is not pinned to the expected local package "
            f"({expected!r}); got {mediapipe!r}"
        )

p12_batch = VCR / "Editor" / "P12" / "P12BatchValidation.cs"
if p12_batch.is_file() and "P11BatchValidation.RunChecks()" not in p12_batch.read_text(encoding="utf-8"):
    errors.append("P12 batch validation no longer inherits the P11 validation chain")

p13_batch = VCR / "Editor" / "P13" / "P13BatchValidation.cs"
if p13_batch.is_file() and "P12BatchValidation.RunChecks()" not in p13_batch.read_text(encoding="utf-8"):
    errors.append("P13 batch validation no longer inherits the P12 validation chain")

# These files must be generated by the pinned Unity editor. Hand-authored
# substitutes are not accepted. Development checks keep the gap visible as a
# warning; release/promotion checks can opt into a strict failure gate.
for path in [
    UNITY / "Packages" / "packages-lock.json",
    UNITY / "ProjectSettings" / "ProjectSettings.asset",
]:
    if not path.is_file():
        message = (
            f"reproducibility evidence still missing: {path.relative_to(ROOT)} "
            "(generate/commit from the pinned Unity editor, do not hand-author)"
        )
        if args.strict_reproducibility:
            errors.append(message)
        else:
            warnings.append(message)

for message in warnings:
    print(f"WARNING: {message}")

if errors:
    for message in errors:
        print(f"ERROR: {message}", file=sys.stderr)
    print(f"Repository structure validation: FAIL ({len(errors)} error(s))", file=sys.stderr)
    raise SystemExit(1)

mode = (
    "strict reproducibility"
    if args.strict_reproducibility
    else "development"
)
print(
    "Repository structure validation: PASS "
    f"(mode={mode}; {len(warnings)} non-blocking warning(s))"
)
