#!/usr/bin/env python3
"""Strict semantic checks for real Unity 6000.3.25f1 reproducibility evidence."""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

root = Path(__file__).resolve().parents[1]
project = root / "unity"
manifest_path = project / "Packages" / "manifest.json"
lock_path = project / "Packages" / "packages-lock.json"
settings_path = project / "ProjectSettings" / "ProjectSettings.asset"
version_path = project / "ProjectSettings" / "ProjectVersion.txt"
problems: list[str] = []

def fail(message: str) -> None:
    problems.append(message)

if not version_path.is_file() or not re.search(
    r"^m_EditorVersion: 6000\.3\.25f1$", version_path.read_text(), re.MULTILINE
):
    fail("Unity editor must be pinned to 6000.3.25f1")

try:
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    direct = manifest["dependencies"]
    if not isinstance(direct, dict) or not direct:
        fail("manifest dependencies missing")
except (OSError, ValueError, KeyError) as exc:
    direct = {}
    fail(f"manifest.json unreadable: {exc}")

expected_direct = {
    "com.unity.render-pipelines.universal": "17.3.0",
    "com.vrmc.gltf": "#v0.131.2",
    "com.vrmc.univrm": "#v0.131.2",
    "com.vrmc.vrm": "#v0.131.2",
    "com.github.homuler.mediapipe": "file:LocalPackages/com.github.homuler.mediapipe-0.16.3.tgz",
    "com.kirurobo.uniwinc": "file:LocalPackages/com.kirurobo.uniwinc",
    "com.ultraleap.tracking": "file:LocalPackages/com.ultraleap.tracking",
}
for name, required in expected_direct.items():
    actual = direct.get(name)
    if not isinstance(actual, str) or (required not in actual if required.startswith("#") else required != actual):
        fail(f"missing or changed pinned manifest dependency {name}: {actual!r}")

if not lock_path.is_file():
    fail("packages-lock.json missing (must be generated by Unity Package Manager)")
else:
    try:
        lock = json.loads(lock_path.read_text(encoding="utf-8"))
        packages = lock["dependencies"]
        if not isinstance(packages, dict) or not packages:
            fail("package lock dependency graph is empty")
        else:
            for name, manifest_value in direct.items():
                entry = packages.get(name)
                if not isinstance(entry, dict):
                    fail(f"direct dependency absent from Unity-generated lock: {name}")
                    continue
                if not isinstance(entry.get("version"), str) or not entry["version"]:
                    fail(f"locked package has no version: {name}")
                if not isinstance(entry.get("source"), str) or not entry["source"]:
                    fail(f"locked package has no source: {name}")
                if entry.get("depth") != 0:
                    fail(f"direct dependency must have depth=0: {name}")
                if isinstance(manifest_value, str) and manifest_value.startswith("https://") and "#" in manifest_value:
                    if entry.get("source") != "git":
                        fail(f"pinned Git dependency must remain Git-sourced: {name}")
                    if not entry.get("hash"):
                        fail(f"pinned Git dependency has no resolved commit hash: {name}")
                if isinstance(manifest_value, str) and manifest_value.startswith("file:"):
                    if entry.get("source") not in ("local", "local-tarball"):
                        fail(f"local dependency unexpectedly resolved from a remote registry: {name}")
    except (OSError, ValueError, KeyError) as exc:
        fail(f"packages-lock.json is not a usable Unity dependency lock: {exc}")

if not settings_path.is_file():
    fail("ProjectSettings.asset missing (must be generated by the pinned Unity editor)")
else:
    settings = settings_path.read_text(encoding="utf-8-sig", errors="replace")
    if len(settings) < 512 or not re.search(r"(?m)^PlayerSettings:", settings):
        fail("ProjectSettings.asset does not resemble Unity-authored serialized PlayerSettings")

for message in problems:
    print("FAIL:", message, file=sys.stderr)
if problems:
    raise SystemExit(1)
print("PASS: Unity 6000.3.25f1 settings and pinned package graph validated")
